package com.esgi.fooders.ui.theme

import androidx.compose.ui.graphics.Color

// Orange Theme - Light
val OrangePrimary = Color(0xFFFF6B00)
val OrangeOnPrimary = Color(0xFFFFFFFF)
val OrangePrimaryContainer = Color(0xFFFFDCC0)
val OrangeOnPrimaryContainer = Color(0xFF2B1700)
val OrangeSecondary = Color(0xFFFF9500)
val OrangeOnSecondary = Color(0xFFFFFFFF)
val OrangeSecondaryContainer = Color(0xFFFFE5CC)
val OrangeOnSecondaryContainer = Color(0xFF271905)
val OrangeTertiary = Color(0xFF4CAF50)
val OrangeOnTertiary = Color(0xFFFFFFFF)
val OrangeTertiaryContainer = Color(0xFFC8E6C9)
val OrangeOnTertiaryContainer = Color(0xFF0F1F04)
val OrangeInversePrimary = Color(0xFFFFB74D)
val OrangeSurfaceTint = Color(0xFFFF6B00)

// Orange Theme - Dark
val OrangePrimaryDark = Color(0xFFFFB74D)
val OrangeOnPrimaryDark = Color(0xFF4A2800)
val OrangePrimaryContainerDark = Color(0xFF6B3D00)
val OrangeOnPrimaryContainerDark = Color(0xFFFFDCC0)
val OrangeSecondaryDark = Color(0xFFFFCC80)
val OrangeOnSecondaryDark = Color(0xFF4A2800)
val OrangeSecondaryContainerDark = Color(0xFF5C3A00)
val OrangeOnSecondaryContainerDark = Color(0xFFFFE5CC)
val OrangeTertiaryDark = Color(0xFF81C784)
val OrangeOnTertiaryDark = Color(0xFF1B3D1C)
val OrangeTertiaryContainerDark = Color(0xFF2E5930)
val OrangeOnTertiaryContainerDark = Color(0xFFC8E6C9)
val OrangeInversePrimaryDark = Color(0xFFFF6B00)
val OrangeSurfaceTintDark = Color(0xFFFFB74D)

// Avocado/Green Theme - Light
val AvocadoPrimary = Color(0xFF66BB6A)
val AvocadoOnPrimary = Color(0xFFFFFFFF)
val AvocadoPrimaryContainer = Color(0xFFC8E6C9)
val AvocadoOnPrimaryContainer = Color(0xFF1B5E20)
val AvocadoSecondary = Color(0xFF9CCC65)
val AvocadoOnSecondary = Color(0xFFFFFFFF)
val AvocadoSecondaryContainer = Color(0xFFDCEDC8)
val AvocadoOnSecondaryContainer = Color(0xFF33691E)
val AvocadoTertiary = Color(0xFF26A69A)
val AvocadoOnTertiary = Color(0xFFFFFFFF)
val AvocadoTertiaryContainer = Color(0xFFB2DFDB)
val AvocadoOnTertiaryContainer = Color(0xFF004D40)
val AvocadoInversePrimary = Color(0xFF81C784)
val AvocadoSurfaceTint = Color(0xFF66BB6A)

// Avocado/Green Theme - Dark
val AvocadoPrimaryDark = Color(0xFF81C784)
val AvocadoOnPrimaryDark = Color(0xFF1B3D1C)
val AvocadoPrimaryContainerDark = Color(0xFF2E5930)
val AvocadoOnPrimaryContainerDark = Color(0xFFC8E6C9)
val AvocadoSecondaryDark = Color(0xFFC5E1A5)
val AvocadoOnSecondaryDark = Color(0xFF2E4522)
val AvocadoSecondaryContainerDark = Color(0xFF3F5830)
val AvocadoOnSecondaryContainerDark = Color(0xFFDCEDC8)
val AvocadoTertiaryDark = Color(0xFF80CBC4)
val AvocadoOnTertiaryDark = Color(0xFF003D37)
val AvocadoTertiaryContainerDark = Color(0xFF00564D)
val AvocadoOnTertiaryContainerDark = Color(0xFFB2DFDB)
val AvocadoInversePrimaryDark = Color(0xFF66BB6A)
val AvocadoSurfaceTintDark = Color(0xFF81C784)

// Cherry/Red Theme - Light
val CherryPrimary = Color(0xFFF44336)
val CherryOnPrimary = Color(0xFFFFFFFF)
val CherryPrimaryContainer = Color(0xFFFFCDD2)
val CherryOnPrimaryContainer = Color(0xFFB71C1C)
val CherrySecondary = Color(0xFFFF5722)
val CherryOnSecondary = Color(0xFFFFFFFF)
val CherrySecondaryContainer = Color(0xFFFFCCBC)
val CherryOnSecondaryContainer = Color(0xFFBF360C)
val CherryTertiary = Color(0xFFFFC107)
val CherryOnTertiary = Color(0xFF000000)
val CherryTertiaryContainer = Color(0xFFFFECB3)
val CherryOnTertiaryContainer = Color(0xFFFF6F00)
val CherryInversePrimary = Color(0xFFEF5350)
val CherrySurfaceTint = Color(0xFFF44336)

// Cherry/Red Theme - Dark
val CherryPrimaryDark = Color(0xFFEF9A9A)
val CherryOnPrimaryDark = Color(0xFF5C1010)
val CherryPrimaryContainerDark = Color(0xFF7F1C1C)
val CherryOnPrimaryContainerDark = Color(0xFFFFCDD2)
val CherrySecondaryDark = Color(0xFFFFAB91)
val CherryOnSecondaryDark = Color(0xFF5C2510)
val CherrySecondaryContainerDark = Color(0xFF803519)
val CherryOnSecondaryContainerDark = Color(0xFFFFCCBC)
val CherryTertiaryDark = Color(0xFFFFD54F)
val CherryOnTertiaryDark = Color(0xFF3D2E00)
val CherryTertiaryContainerDark = Color(0xFF5C4500)
val CherryOnTertiaryContainerDark = Color(0xFFFFECB3)
val CherryInversePrimaryDark = Color(0xFFF44336)
val CherrySurfaceTintDark = Color(0xFFEF9A9A)

// Common colors - Light
val BackgroundLight = Color(0xFFFAFAFA)
val OnBackgroundLight = Color(0xFF1C1B1F)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF1C1B1F)
val SurfaceVariantLight = Color(0xFFF5F5F5)
val OnSurfaceVariantLight = Color(0xFF49454F)
val OutlineLight = Color(0xFF79747E)
val OutlineVariantLight = Color(0xFFE0E0E0)
val ErrorLight = Color(0xFFFF3D00)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFCDD2)
val OnErrorContainerLight = Color(0xFF410002)
val InverseOnSurfaceLight = Color(0xFFF4EFF4)
val InverseSurfaceLight = Color(0xFF313033)
val ShadowLight = Color(0xFF000000)
val ScrimLight = Color(0xFF000000)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF7F2F7)
val SurfaceContainerLight = Color(0xFFF1ECF1)
val SurfaceContainerHighLight = Color(0xFFEBE6EB)
val SurfaceContainerHighestLight = Color(0xFFE6E1E5)

// Common colors - Dark
val BackgroundDark = Color(0xFF121212)
val OnBackgroundDark = Color(0xFFE6E1E5)
val SurfaceDark = Color(0xFF1C1B1F)
val OnSurfaceDark = Color(0xFFE6E1E5)
val SurfaceVariantDark = Color(0xFF2C2C2C)
val OnSurfaceVariantDark = Color(0xFFCAC4D0)
val OutlineDark = Color(0xFF938F99)
val OutlineVariantDark = Color(0xFF49454F)
val ErrorDark = Color(0xFFFF6659)
val OnErrorDark = Color(0xFF5C0000)
val ErrorContainerDark = Color(0xFF7F0000)
val OnErrorContainerDark = Color(0xFFFFDAD4)
val InverseOnSurfaceDark = Color(0xFF313033)
val InverseSurfaceDark = Color(0xFFE6E1E5)
val ShadowDark = Color(0xFF000000)
val ScrimDark = Color(0xFF000000)
val SurfaceContainerLowestDark = Color(0xFF0D0D0D)
val SurfaceContainerLowDark = Color(0xFF1C1B1F)
val SurfaceContainerDark = Color(0xFF211F26)
val SurfaceContainerHighDark = Color(0xFF2B2930)
val SurfaceContainerHighestDark = Color(0xFF36343B)

// Gradient colors for cards (used across themes)
object GradientColors {
    val OrangeStart = Color(0xFFFF6B00)
    val OrangeEnd = Color(0xFFFF9500)
    val GreenStart = Color(0xFF66BB6A)
    val GreenEnd = Color(0xFF26A69A)
    val BlueStart = Color(0xFF2196F3)
    val BlueEnd = Color(0xFF00BCD4)
    val PurpleStart = Color(0xFF9C27B0)
    val PurpleEnd = Color(0xFFE91E63)
    val RedStart = Color(0xFFF44336)
    val RedEnd = Color(0xFFFF5722)
}

// Vibrant accent colors
object AccentColors {
    val Blue = Color(0xFF2196F3)
    val BlueLight = Color(0xFFBBDEFB)
    val Purple = Color(0xFF9C27B0)
    val PurpleLight = Color(0xFFE1BEE7)
    val Pink = Color(0xFFE91E63)
    val PinkLight = Color(0xFFF8BBD0)
    val Teal = Color(0xFF009688)
    val TealLight = Color(0xFFB2DFDB)
    val Lime = Color(0xFFCDDC39)
    val LimeLight = Color(0xFFF0F4C3)
    val Amber = Color(0xFFFFC107)
    val AmberLight = Color(0xFFFFECB3)
}
